# Generated by Django 2.2.5 on 2019-09-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190908_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
